### ISSUE TITLE
🐛 Bug Report: exception thrown with LlamaIndex new workflow API

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#2394]
### Which component is this bug for?

Llamaindex Instrumentation

### 📜 Description

When using the new [workflows API](https://www.llamaindex.ai/blog/introducing-workflows-beta-a-new-way-to-create-complex-ai-applications-with-llamaindex), there's an exception thrown:
```
Traceback (most recent call last):
File "/app/.venv/lib/python3.11/site-packages/opentelemetry/context/init.py", line 152, in detach
_RUNTIME_CONTEXT.detach(token)
File "/app/.venv/lib/python3.11/site-packages/opentelemetry/context/contextvars_context.py", line 50, in detach
self._current_context.reset(token)  # type: ignore
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: <Token var=<ContextVar name='current_context' default={} at 0x7bd2c6f07470> at 0x7bd1b27cbf40> was created in a different Context
```

### 👟 Reproduction steps

-

### 👍 Expected behavior

-

### 👎 Actual Behavior with Screenshots

-

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by FelipeSantos-Ascensus** [comment]
I am not sure if this will help, but I was able to generate data using this:

```
from openinference.instrumentation.llama_index import LlamaIndexInstrumentor
from arize.otel import register

# Setup OTel via our convenience function
tracer_provider = register(
    space_id = "your-space-id", # in app space settings page
    api_key = "your-api-key", # in app space settings page
    project_name = "your-project-name", # name this to whatever you would like
)

 # Finish automatic instrumentation
LlamaIndexInstrumentor().instrument(tracer_provider=tracer_provider)
```

**Comment by galkleinman** [comment]
Closing the issue as it was resolved here: https://github.com/traceloop/openllmetry/pull/2421.
