### ISSUE TITLE
🐛 Bug Report: Always getting exception when Traceloop.init()

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#340]
### Which component is this bug for?

Traceloop SDK

### 📜 Description

```python
from dotenv import load_dotenv
import os
load_dotenv()

from traceloop.sdk import Traceloop
Traceloop.init()
```

I have created a .env file which contains my trace loop api key.

When run above program, it always report error as follows, am I doing anything wrong? Thanks

```
(py310) gyliu@guangyas-air openllmetry % /Users/gyliu/py310/bin/python /Users/gyliu/go/src/github.com/traceloop/openllmetry/packages/sample-app/sample_app/test.py
Traceback (most recent call last):
  File "/Users/gyliu/go/src/github.com/traceloop/openllmetry/packages/sample-app/sample_app/test.py", line 6, in <module>
    Traceloop.init()
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/__init__.py", line 64, in init
    Traceloop.__fetcher.run()
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 55, in run
    refresh_data(
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 144, in refresh_data
    response = fetch_url(f"{base_url}/v1/traceloop/prompts", api_key)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 101, in fetch_url
    raise requests.exceptions.HTTPError(response=response)
requests.exceptions.HTTPError
```

### 👟 Reproduction steps

Run the python script as above

### 👍 Expected behavior

Run this program

```python
from dotenv import load_dotenv
import os
load_dotenv()

from traceloop.sdk import Traceloop
Traceloop.init()
```

### 👎 Actual Behavior with Screenshots

error as follows

```
(py310) gyliu@guangyas-air openllmetry % /Users/gyliu/py310/bin/python /Users/gyliu/go/src/github.com/traceloop/openllmetry/packages/sample-app/sample_app/test.py
Traceback (most recent call last):
  File "/Users/gyliu/go/src/github.com/traceloop/openllmetry/packages/sample-app/sample_app/test.py", line 6, in <module>
    Traceloop.init()
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/__init__.py", line 64, in init
    Traceloop.__fetcher.run()
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 55, in run
    refresh_data(
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 144, in refresh_data
    response = fetch_url(f"{base_url}/v1/traceloop/prompts", api_key)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gyliu/py310/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/gyliu/py310/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 101, in fetch_url
    raise requests.exceptions.HTTPError(response=response)
requests.exceptions.HTTPError
```

### 🤖 Python Version

3.10

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by nirga** [comment]
Might be related to #290. Can you share the envs you're defining? (Without values ofc)

**Comment by gyliu513** [comment]
Just one value “ TRACELOOP_API_KEY=xxx”

**Comment by nirga** [comment]
This error (which needs to be better as per #290) means the api key is invalid. Can you try regenerating it in the platform and see if solves it?

**Comment by gyliu513** [comment]
@nirga still does not work even I re-generate a new key, got same error. Does it works in your env?

```console
(pytraceloop) gyliu@guangyas-air test % cat .env
TRACELOOP_API_KEY="641e8e7e39a3fdxxxxxxxxxxx"
```

```console
(pytraceloop) gyliu@guangyas-air test % python t.py
Traceback (most recent call last):
  File "/Users/gyliu/test/t.py", line 7, in <module>
    Traceloop.init()
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/__init__.py", line 62, in init
    Traceloop.__fetcher.run()
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 55, in run
    refresh_data(
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 144, in refresh_data
    response = fetch_url(f"{base_url}/v1/traceloop/prompts", api_key)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 101, in fetch_url
    raise requests.exceptions.HTTPError(response=response)
requests.exceptions.HTTPError
```

```console
(pytraceloop) gyliu@guangyas-air test % python
Python 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by nirga** [comment]
@gyliu513 thanks I managed to reproduce it locally. It's weird since it only happens with `dotenv`. If you `export TRACELOOP_API_KEY=...` it works fine. I'll look into this now but as a workaround for now you can set the environment variable directly.

**Comment by gyliu513** [comment]
Thanks @nirga , still does not work even export env, I was exposing my whole api key here, but no worry, I will delete this one and re-generate a new one, just want to share with you the whole content here.

```console
(pytraceloop) gyliu@guangyas-air test % export TRACELOOP_API_KEY="641e8e7e39a3fdb9a1bd056001b5752544c85a4234e6b24bec607aee116949502ea73fa8b2605f17e5a31121a35b5326"
```
```console
(pytraceloop) gyliu@guangyas-air test % cat t.py
import os

from traceloop.sdk import Traceloop
print(os.getenv("TRACELOOP_API_KEY"))
Traceloop.init()
```
```console
(pytraceloop) gyliu@guangyas-air test % python t.py
641e8e7e39a3fdb9a1bd056001b5752544c85a4234e6b24bec607aee116949502ea73fa8b2605f17e5a31121a35b5326
Traceback (most recent call last):
  File "/Users/gyliu/test/t.py", line 5, in <module>
    Traceloop.init()
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/__init__.py", line 62, in init
    Traceloop.__fetcher.run()
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 55, in run
    refresh_data(
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 144, in refresh_data
    response = fetch_url(f"{base_url}/v1/traceloop/prompts", api_key)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 101, in fetch_url
    raise requests.exceptions.HTTPError(response=response)
requests.exceptions.HTTPError
```

**Comment by nirga** [comment]
Scratch that - found the issue you had. You need to remove the `"`
`TRACELOOP_API_KEY=641e8e7e39a3fdxxxxxxxxxxx`
and not
`TRACELOOP_API_KEY="641e8e7e39a3fdxxxxxxxxxxx"`

**Comment by gyliu513** [comment]
No luck...


```
(pytraceloop) gyliu@guangyas-air test % export TRACELOOP_API_KEY=641e8e7e39a3fdb9a1bd056001b5752544c85a4234e6b24bec607aee116949502ea73fa8b2605f17e5a31121a35b5326
(pytraceloop) gyliu@guangyas-air test % python t.py
641e8e7e39a3fdb9a1bd056001b5752544c85a4234e6b24bec607aee116949502ea73fa8b2605f17e5a31121a35b5326
Traceback (most recent call last):
  File "/Users/gyliu/test/t.py", line 5, in <module>
    Traceloop.init()
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/__init__.py", line 62, in init
    Traceloop.__fetcher.run()
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 55, in run
    refresh_data(
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 144, in refresh_data
    response = fetch_url(f"{base_url}/v1/traceloop/prompts", api_key)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "/Users/gyliu/pytraceloop/lib/python3.10/site-packages/traceloop/sdk/fetcher.py", line 101, in fetch_url
    raise requests.exceptions.HTTPError(response=response)
requests.exceptions.HTTPError
```

**Comment by nirga** [comment]
@gyliu513 want to hop over to slack, might be easier to chat there? 
https://traceloop.com/slack

**Comment by nirga** [comment]
After a slack chat, we manage to resolve this - the API key wasn't valid. For future references, go to https://app.traceloop.com/settings/api-keys to generate API keys and use them without `"`.
