### ISSUE TITLE
🐛 Bug Report: Traceloop.init() will init all LLM Providers

### ISSUE THREAD

**Issue by gyliu513** [traceloop/openllmetry#343]
### Which component is this bug for?

Anthropic Instrumentation

### 📜 Description

If there are sth wrong with LLM Provider instrumentation code, the Traceloop.init() will be failed. One example is I want to run a watsonx service, and llamaindex init failed, this caused I cannot run my watsonx service.

### 👟 Reproduction steps

```console
(py311) gyliu@Guangyas-MacBook-Air openllmetry % /Users/gyliu/py311/bin/python /Users/gyliu/go/src/github.com/traceloop/openllmetry/
packages/sample-app/sample_app/watsonx_generate.py
Traceloop syncing configuration and prompts
Traceloop exporting traces to https://api.traceloop.com authenticating with bearer token

/Users/gyliu/py311/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatAnyscale`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/chat_models/__init__.py:31: LangChainDeprecationWarning: Importing chat models from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.chat_models import ChatOpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/embeddings/__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.embeddings import HuggingFaceBgeEmbeddings`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/embeddings/__init__.py:29: LangChainDeprecationWarning: Importing embeddings from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.embeddings import HuggingFaceEmbeddings`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import AI21`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import Cohere`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import FakeListLLM`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
/Users/gyliu/py311/lib/python3.11/site-packages/langchain/llms/__init__.py:548: LangChainDeprecationWarning: Importing LLMs from langchain is deprecated. Importing from langchain will no longer be supported as of langchain==0.2.0. Please import from langchain-community instead:

`from langchain_community.llms import OpenAI`.

To install langchain-community run `pip install -U langchain-community`.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/gyliu/go/src/github.com/traceloop/openllmetry/packages/sample-app/sample_app/watsonx_generate.py", line 9, in <module>
    Traceloop.init()
  File "/Users/gyliu/py311/lib/python3.11/site-packages/traceloop/sdk/__init__.py", line 152, in init
    Traceloop.__tracer_wrapper = TracerWrapper(
                                 ^^^^^^^^^^^^^^
  File "/Users/gyliu/py311/lib/python3.11/site-packages/traceloop/sdk/tracing/tracing.py", line 111, in __new__
    init_instrumentations()
  File "/Users/gyliu/py311/lib/python3.11/site-packages/traceloop/sdk/tracing/tracing.py", line 266, in init_instrumentations
    init_llama_index_instrumentor()
  File "/Users/gyliu/py311/lib/python3.11/site-packages/traceloop/sdk/tracing/tracing.py", line 360, in init_llama_index_instrumentor
    from opentelemetry.instrumentation.llamaindex import LlamaIndexInstrumentor
  File "/Users/gyliu/py311/lib/python3.11/site-packages/opentelemetry/instrumentation/llamaindex/__init__.py", line 14, in <module>
    from opentelemetry.instrumentation.llamaindex.custom_llm_instrumentor import CustomLLMInstrumentor
  File "/Users/gyliu/py311/lib/python3.11/site-packages/opentelemetry/instrumentation/llamaindex/custom_llm_instrumentor.py", line 14, in <module>
    from llama_index.llms.custom import CustomLLM
  File "/Users/gyliu/py311/lib/python3.11/site-packages/llama_index/__init__.py", line 17, in <module>
    from llama_index.embeddings.langchain import LangchainEmbedding
  File "/Users/gyliu/py311/lib/python3.11/site-packages/llama_index/embeddings/__init__.py", line 18, in <module>
    from llama_index.embeddings.huggingface import (
  File "/Users/gyliu/py311/lib/python3.11/site-packages/llama_index/embeddings/huggingface.py", line 17, in <module>
    from llama_index.llms.huggingface import HuggingFaceInferenceAPI
  File "/Users/gyliu/py311/lib/python3.11/site-packages/llama_index/llms/__init__.py", line 25, in <module>
    from llama_index.llms.litellm import LiteLLM
  File "/Users/gyliu/py311/lib/python3.11/site-packages/llama_index/llms/litellm.py", line 28, in <module>
    from llama_index.llms.litellm_utils import (
  File "/Users/gyliu/py311/lib/python3.11/site-packages/llama_index/llms/litellm_utils.py", line 4, in <module>
    from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'
```

### 👍 Expected behavior

Enable init can only init a specified llm provider.

### 👎 Actual Behavior with Screenshots

as `Reproduction steps`

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by gyliu513** [comment]
@nirga comments?

**Comment by gyliu513** [comment]
If you apply this PR https://github.com/traceloop/openllmetry/pull/341, and run a sample app, some instrumentation code will be failed as above.

**Comment by nirga** [comment]
Hmm, this doesn't look like an issue with the SDK but rather with the sample app. Looks like we're using a really old llamaindex version which might cause issues so I'll try to upgrade and we'll see if this is still happening.

**Comment by gyliu513** [comment]
@nirga Yes, but do you think we need to initialize the traceloop based on LLM Providers? I think there is no need to initialize all LLM providers at init time when just running on specified app based on one specified model, comments?

**Comment by nirga** [comment]
@gyliu513 I think that's part of the magic, no? Similar to the OpenTelemetry original auto-instrument capabilities.
But I do want to offer a way to override this and explicitly set which instrumentations to enable, see #258.

**Comment by gyliu513** [comment]
Good, thanks @nirga , do you think we can close this one and focus on #258?
