### ISSUE TITLE
🐛 Bug Report: exceptions on instrumentation errors 

### ISSUE THREAD

**Issue by nirga** [traceloop/openllmetry#670]
### Which component is this bug for?

All Packages

### 📜 Description

Instrumentations may fail sometime - due to version issues, incompatible APIs, etc. Right now, we throw exceptions in these cases which is bad. We should wrap the parts where we try to instrument the library in the different instrumentations with `try... except` and log the errors instead of failing.

### 👟 Reproduction steps

Might be difficult, as it depends on specific environments.

### 👍 Expected behavior

Log an error, report it to Posthog and continue

### 👎 Actual Behavior with Screenshots

we've seen a customer with `qdrant-client==1.7.0` failing with this error:
```
C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\snowflake\connector\options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (14.0.2), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
WARNING:snowflake.connector.cursor:Failed to import ArrowResult. No Apache Arrow result set format can be used. ImportError: DLL load failed while importing arrow_iterator: No se encontró el proceso especificado.
Traceloop syncing configuration and prompts
Traceloop exporting traces to https://api.traceloop.com/ authenticating with bearer token

Traceback (most recent call last):
  File "C:\Users\macha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\macha\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\__main__.py", line 4, in <module>
    uvicorn.main()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\main.py", line 437, in main
    run(app, **kwargs)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\main.py", line 463, in run
    server.run()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\macha\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\macha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\server.py", line 67, in serve
    config.load()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\config.py", line 458, in load
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Users\macha\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\settings.py", line 8, in <module>
    from web_apps.api import router as api_router
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\web_apps\api.py", line 2, in <module>
    from web_apps.knowledge_base import views as knowledge_base
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\web_apps\knowledge_base\views.py", line 11, in <module>
    from web_apps.knowledge_base.services import KnowledgeBaseServices, SnowflakeServices
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\web_apps\knowledge_base\services.py", line 9, in <module>
    from web_apps.utils.cassandra_utils import CassandraUtils
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\web_apps\utils\cassandra_utils.py", line 1, in <module>
    from brain.inference.inference_service import InferenceService
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\brain\inference\inference_service.py", line 9, in <module>
    from web_apps.utils.lambda_utils import LambdaWrapper
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\web_apps\utils\lambda_utils.py", line 9, in <module>
    from copilot_lambda_service.lambda_handler_copilot import (
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\copilot_lambda_service\lambda_handler_copilot.py", line 13, in <module>
    from copilot_lambda_service.interactions.global_interactions import process_interaction
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\copilot_lambda_service\interactions\global_interactions.py", line 8, in <module>
    from brain.inference.paths.data_copilot_path import DataCopilotPath
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\.\brain\inference\paths\data_copilot_path.py", line 64, in <module>
    Traceloop.init(disable_batch=True,
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\traceloop\sdk\__init__.py", line 160, in init
    Traceloop.__tracer_wrapper = TracerWrapper(
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\traceloop\sdk\tracing\tracing.py", line 119, in __new__
    init_instrumentations()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\traceloop\sdk\tracing\tracing.py", line 403, in init_instrumentations
    init_qdrant_instrumentor()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\traceloop\sdk\tracing\tracing.py", line 470, in init_qdrant_instrumentor
    instrumentor.instrument()
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\opentelemetry\instrumentation\instrumentor.py", line 114, in instrument
    result = self._instrument(  # pylint: disable=assignment-from-no-return
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\opentelemetry\instrumentation\qdrant\__init__.py", line 50, in _instrument
    wrap_function_wrapper(
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\wrapt\wrappers.py", line 870, in wrap_function_wrapper
    return wrap_object(module, name, FunctionWrapper, (wrapper,))
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\wrapt\wrappers.py", line 816, in wrap_object
    (parent, attribute, original) = resolve_path(module, name)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\wrapt\wrappers.py", line 808, in resolve_path
    original = lookup_attribute(parent, attribute)
  File "C:\Users\macha\Documents\Simetrik\DA\mnemosina\venv\lib\site-packages\wrapt\wrappers.py", line 800, in lookup_attribute
    return getattr(parent, attribute)
AttributeError: type object 'QdrantClient' has no attribute 'upload_points'

Process finished with exit code 1
```

### 👀 Have you spent some time to check if this bug has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

None

**Comment by colesnic** [comment]
I can try to take a stab at this.

**Comment by varaarul** [comment]
will look at this!
